### ISSUE TITLE
Search Feature not working

### ISSUE THREAD

**Issue by camilokorea** [tripitakit/xeno-canto#3]
Hi Devs

There is a problem with this library?

Seems that the SEARCH feature is not working in my dev environment, here is my code. For any reason the callback is not executed any more

                    var XenoCanto = require('xeno-canto');
                    var birdSing = new XenoCanto();

                    console.log(req.query.sciname);

                    birdSing.search(req.query.sciname, function (self) {
                        //code no entering more to this callback
                        console.log(self.entity.recordings.length);

                        if (self.entity.recordings.length > 0) {

                            var request = require('request');

                            var timeoutInMilliseconds = 10 * 1000;

                            var opts = {
                                url: self.entity.recordings[0].file,
                                method: 'GET',
                                timeout: timeoutInMilliseconds,
                                headers:
                                {
                                    'User-Agent': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163 Safari/537.36'
                                }
                            };

                            request(opts, function (err, res, url) {

                                if (err) {

                                    body.error = err;

                                    response.send(body);

                                    return;

                                } else {

                                    var sound = {
                                        file: res.request.uri.href,
                                        url: self.entity.recordings[0].url
                                    };

                                    body.response = sound;
                                    response.send(body);
                                }

                            });
                        } else {
                            body.response = null;
                            response.send(body);
                        }

                    });

**Comment by tripitakit** [comment]
thank to Camilo, fixed in v0.0.4.
